### PR TITLE
kinetics: Add Park's 2T model to calculate K_eq

### PR DESCRIPTION
**Pull request by Jianshu-Wu**
Original from the Park's 2T model, using A1 - A5 parameters to calculate the K_eq.

### CODE REVIEW

**Comment by pajacobs-ghub** [comment]
With respect to -no_compact_unwind, I am waiting on a resolution for this: https://forum.dlang.org/thread/twklitirpdzocsvfswnw@forum.dlang.org

**Comment by KulaLAForU** [comment]
Ah, I'm sorry for this, I found this ater pulling it this morning and realizing it caused the crash. 
Hope it can be fix.

**Comment by uqngibbo** [comment]
Hi Jianshu, 

It looks like you accidentally added a bunch of temporary files in the [f6e4da6](https://github.com/gdtk-uq/gdtk/pull/63/commits/f6e4da643426884396d238066f9d441b4de0bb01) commit, mostly in the build directory.

Do you mind making another commit that removes these files, and then squashing all of your commits into a single commit, so that I can review your changes properly.

Thanks,
Nick

**Comment by KulaLAForU** [comment]
Thanks, and sorry for wasting your time, I'll fix it and submit later.

**Pull request closed without merging**
